# Generated by Django 5.2.17 on 2026-08-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Saree', 'Saree'), ('Makeup', 'Makeup'), ('Electronics', 'Electronics'), ('Sandals', 'Sandals'), ('Jewellery', 'Jewellery'), ('Kurtha Set', 'Kurtha Set')], default='Saree', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.CharField(default='https://via.placeholder.com/200', max_length=500),
        ),
    ]
